### ISSUE TITLE
Your trained model is missing

### ISSUE THREAD

**Issue by halolimat** [geoai-lab/NeuroTPR#1]
Hello,

Thanks very much for making your work available online. I just want to ask if you can share your model you trained and reported the results for in your paper. It is missing from the folder `../Model/outputs/NeuroTPR2.json`

Thanks in advance!

**Comment by Jim-King** [comment]
No problem, I will share my trained model's weights file recently. Sorry, but the files are too big to upload to Github.

**Comment by Jim-King** [comment]
> Hello,
> 
> Thanks very much for making your work available online. I just want to ask if you can share your model you trained and reported the results for in your paper. It is missing from the folder `../Model/outputs/NeuroTPR2.json`
> 
> Thanks in advance!

Just upload the model we trained and used to report the results in the folder ../Model/outputs
